services:
  nginx:
    image: nginx:stable-alpine
    container_name: "${APP_NAME}-nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/var/www/html
    depends_on:
      - php
      - mysql
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - laravel-net
  php:
    build:
      context: ./php
      dockerfile: php.dockerfile
    container_name: "${APP_NAME}-php"
    volumes:
      - ./web:/var/www/html
    networks:
      - laravel-net
  mysql:
    image: mysql:latest
    container_name: "${APP_NAME}-mysql"
    env_file:
      - ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - laravel-net
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: "${APP_NAME}-phpmyadmin"
    environment:
      PMA_HOST: mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - laravel-net
  composer:
    build:
      context: ./composer
      dockerfile: composer.dockerfile
    container_name: "${APP_NAME}-composer"
    volumes:
      - ./web:/var/www/html
    networks:
      - laravel-net
  artisan:
    build:
      context: ./php
      dockerfile: php.dockerfile
    container_name: "${APP_NAME}-artisan"
    volumes:
      - ./web:/var/www/html
    ports:
      - "${ARTISAN_PORT}:8000"
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel-net
  npm:
    image: node:alpine
    container_name: "${APP_NAME}-npm"
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./web:/var/www/html
    networks:
      - laravel-net
  redis:
    image: redis:alpine
    container_name: "${APP_NAME}-redis"
    networks:
      - laravel-net
  mailhog:
    image: mailhog/mailhog
    container_name: "${APP_NAME}-mailhog"
    ports:
      - "${MAILHOG_PORT}:8025"
    networks:
      - laravel-net
networks:
  laravel-net: